### ISSUE TITLE
Problema con la cantidad de muestras del archivo Curvas_Medidas_Motor_2024.xlsx

### ISSUE THREAD

**Issue by FGalvagno** [FGalvagno/Sistemas-de-Control#1]
Buenas @Julianpucheta ,

Estoy teniendo un problema para determinar las funciones de transferencia del motor a fín de obtener las constantes del motor (Item 5).

Las funciones de transferencia que quiero obtener son:

![image](https://github.com/FGalvagno/sistemas-de-control/assets/123911256/948118ea-0895-4c4e-83bf-61810471afad)

La primera función de transferencia la pude aproximar, pese a tener solo cuatro muestras en el transitorio del archivo (desde el dato número 703 al 707).  A partir de esta funcion y aproximando Ra con la corriente de arranque y suponiendo Ki=Km logré despejar el valor de Bm. Restan las constantes Jm y La

Para obtener las constantes del motor restantes, decidi trabajar sobre la segunda función de transferencia, W_r/T_L

El problema ocurre al identificar la segunda función. Todos los transitorios que aplican carga (ejemplo: muestras 16683-16684) tienen solo una muestra en el archivo. Aparentemente la dinámica es muy rápida para esos puntos.

¿Como se podría encarar este problema? El código que estoy usando para el item 5 es [este.](https://github.com/FGalvagno/sistemas-de-control/blob/23399e39c92a733239505b7a72b1810f31d9f4a3/Pr%C3%A1ctico%201%20-%20Representaci%C3%B3n%20de%20sistemas%20y%20controladores/mot5.m)

**Comment by Julianpucheta** [comment]
Bm tiene que ser positivo, si te ha dado negativo, puedes asigarle cero.

**Comment by FGalvagno** [comment]
Buenas tardes,

Sigo sin lograr despejar las variables. El proceso que realicé fue el de comparar estas dos funciones de transferencia:

![image](https://github.com/FGalvagno/sistemas-de-control/assets/123911256/ad48ec3e-29e0-4f8b-ab40-0da0b0368e32)

- _Ra_ la aproximé con el valor del primer pico de la corriente y la tensión de entrada.
- El resto de las variables las calcule comparando numeradores y denominadores.

En la simulación, las curvas son cercanas pero no exactamente iguales. Si supongo iguales los valores de Ki y Km la simulacion directamente me da mal.

Tambien tengo la duda de si solo con la función de transferencia Va/Wr y la aproximación de Ra puedo calcular todas las constantes del motor, ya que en varios códigos que encontré tambien se calcula Va/Tl para modelar las dos entradas.

**Comment by Julianpucheta** [comment]
En en numerador, te queda Ki en el primer cociente, si pasás La al denominador.
Así, te querda que Ki=K
T1*T2=Jm*La
Jm*Ra=(T1+T2)
